### PR TITLE
runsc: Allow map host user to non-root user in rootless mode

### LINKED ISSUE #9918: gVisor unprivileged user can't access file in rootless mode
### Description

While in rootless mode, the container UID is the same as the UID of running runsc, in the container we can't access the file belongs to the host UID.

I want to know how to achieve this. So that in rootless mode, the unprivileged user can access the host file with the same UID.

### Steps to reproduce

using following OCI spec

`test@test-VirtualBox:~/test$ id

uid=1000(test) gid=1000(test) groups=1000(test),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),122(lpadmin),135(lxd),136(sambashare)

test@test-VirtualBox:~/test$ ./runsc -rootless -root /home/test -ignore-cgroups --network host run abc

touch /home/test/bb

touch: cannot touch '/home/test/bb': Permission denied

`

`{

    "ociVersion": "1.0.0",

    "process": {

        "user": {

            "uid": 1000,

            "gid": 1000

        },

        "args": [

            "sh"

        ],

        "env": [

            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",

            "TERM=xterm"

        ],

        "cwd": "/",

        "capabilities": {

            "bounding": [

                "CAP_AUDIT_WRITE",

                "CAP_KILL",

                "CAP_NET_BIND_SERVICE"

            ],

            "effective": [

                "CAP_AUDIT_WRITE",

                "CAP_KILL",

                "CAP_NET_BIND_SERVICE"

            ],

            "inheritable": [

                "CAP_AUDIT_WRITE",

                "CAP_KILL",

                "CAP_NET_BIND_SERVICE"

            ],

            "permitted": [

                "CAP_AUDIT_WRITE",

                "CAP_KILL",

                "CAP_NET_BIND_SERVICE"

            ]

        },

        "rlimits": [

            {

                "type": "RLIMIT_NOFILE",

                "hard": 1024,

                "soft": 1024

            }

        ]

    },

    "root": {

        "path": "/",

        "readonly": true

    },

    "hostname": "runsc",

    "mounts": [

        {

            "destination": "/proc",

            "type": "proc",

            "source": "proc"

        },

        {

            "destination": "/dev",

            "type": "tmpfs",

            "source": "tmpfs"

        },

        {

            "destination": "/sys",

            "type": "sysfs",

            "source": "sysfs",

            "options": [

                "nosuid",

                "noexec",

                "nodev",

                "ro"

            ]

        },

        {

                "destination":"/home/test",

                "type":"bind",

                "source":"/home/test",

                "options":[

                        "rbind",

                        "rw"

                ]

        }

    ],

    "linux": {

        "namespaces": [

            {

                "type": "pid"

            },

            {

                "type": "network"

            },

            {

                "type": "ipc"

            },

            {

                "type": "uts"

            },

            {

                "type": "mount"

            }

        ]

    }

}

`

### runsc version

_No response_

### docker version (if using docker)

_No response_

### uname

_No response_

### kubectl (if using Kubernetes)

_No response_

### repo state (if built from source)

_No response_

### runsc debug logs (if available)

_No response_

### PR DESCRIPTION
**Pull request by terenceli**
Fix #9918.

Currently, the rootless mode(runsc is called by no-root user) is not working well with the filesystem if we uses a non-root user in runsc container. This is because the runsc is mapping the host non-root user to root-user in container.

In some cases we need to map the host non-root user to runsc container non-root user (with the same uid).

After this patch, the following filesystem operations works well.

test@test-virtual-machine:~/test$ ./runsc   -ignore-cgroups --network host run abc
id
uid=1000(test) gid=1000(test) groups=1000(test)
touch /tmp/runsctest
echo aaa > /tmp/runsctest
ls -lh /tmp/runsctest
-rw-r--r-- 1 test test 4 Jun 29 18:46 /tmp/runsctest
exit
test@test-virtual-machine:~/test$ ls -lh /tmp/runsctest
-rw-r--r-- 1 test test 4  6月 29 18:46 /tmp/runsctest
test@test-virtual-machine:~/test$ cat /tmp/runsctest

### CODE REVIEW

File: runsc/sandbox/sandbox.go [hunk 1]
```diff
@@ -1293,6 +1304,60 @@ func (s *Sandbox) createSandboxProcess(conf *config.Config, args *Args, startSyn
...
+                }
+        }
+
+	if !uidFound || !gidFound {
+		return fmt.Errorf("current host uid(%d) or gid(%d) has no mapping in container", euid, egid)
+	}
+
+	// Make sure the specified UID & GID is the same as the host user map to
+	if cuid != specUID {
+		return fmt.Errorf("host uid %d can't map to container uid %d, expected %d", euid, specUID, cuid)
```
Comment (avagin) [inline runsc/sandbox/sandbox.go]: I don't understand this check. Why should the current uid/gid match the container process uid/gid?

Comment (terenceli) [reply runsc/sandbox/sandbox.go]: > I don't understand this check. Why should the current uid/gid match the container process uid/gid?

Yes, I'm not sure is this correct?

Here I add this check is to make sure "the host non-root user can only start container with the corresponding user that he maps to."

Here I think we should clarify "What the meaning if one non-root user start a container process using another user's UID?" Should we allow it? Maybe we should check how crun/podman does it.

**Comment by avagin** [comment]
I think we need to do the same thing that crun does.

> Should we here use the mapped container UID(my current patch) or

This covers your case, but actually the current user is often non-mapped to the container user namespace.

**Comment by terenceli** [comment]
> I think we need to do the same thing that crun does.

Just push a new revision.

> 
> > Should we here use the mapped container UID(my current patch) or
> 
> This covers your case, but actually the current user is often non-mapped to the container user namespace.

**Comment by avagin** [comment]
@terenceli could you take a look at https://github.com/avagin/gvisor/commit/915f3b8a3893509f72880625a406e585281b240c. In this version, user and group IDs are passed in arguments. I think it looks a bit cleaner this way.

**Comment by terenceli** [comment]
> @terenceli could you take a look at [avagin@915f3b8](https://github.com/avagin/gvisor/commit/915f3b8a3893509f72880625a406e585281b240c). In this version, user and group IDs are passed in arguments. I think it looks a bit cleaner this way.

Yes, it's more clean. I have just tested it, it looks good to me.

**Comment by avagin** [comment]
@terenceli could you take these changes in your pr?

**Comment by terenceli** [comment]
> @terenceli could you take these changes in your pr?

@avagin I have pushed a new one. 
Thanks.
