### PR TITLE
Fix EOFs when reading from an empty canon->noncanon PTY

### LINKED ISSUE #9953: Switching from canonical to non-canonical mode in a PTY can cause EOF when reading
### Description

I think this line of code: https://github.com/google/gvisor/blob/2c8e77f5c1d20b376d13467381c2c65bae27172e/pkg/sentry/fsimpl/devpts/line_discipline.go#L157 should be `len(l.inQueue.buffer) > 0` rather than `true`. Otherwise, it seems like switching from canonical to non-canonical mode in a PTY, then reading from the input, could cause an EOF. Making this change fixes my reproduction below, but I'm quite new to this codebase so perhaps I'm mistaken about what's going on.

### Steps to reproduce

Install IPython and create a Python file:

```
import IPython
IPython.embed()
```

Run this Python file within a pty. One option might be `import pty; pty.spawn(["python", "main.py"])`

Press question mark + enter a few times; you should see an EOF error.

### runsc version

_No response_

### docker version (if using docker)

_No response_

### uname

Linux ip-10-1-5-239 5.15.0-1048-aws #53~20.04.1-Ubuntu SMP Wed Oct 4 16:44:20 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### kubectl (if using Kubernetes)

_No response_

### repo state (if built from source)

release-20240122.0-27-gac416763d

### runsc debug logs (if available)

_No response_

### PR DESCRIPTION
**Pull request by thecodingwizard**
When switching from canonical to non-canonical mode, only mark inQueue as readable if there is input to be read. This fixes a bug where a program running in a PTY in canonical mode switches to non-canonical mode with nothing in the canonical read buffer, and then proceeds to read from the standard input, which erroneously results in an EOF error.

Closes #9953

### CODE REVIEW

**Comment by kevinGC** [comment]
Thanks for the PR! Could you add a test to [test/syscalls/linux/pty.cc](https://github.com/google/gvisor/blob/master/test/syscalls/linux/pty.cc)? Something similar to `SwitchCanonToNoncanon` should work.

**Comment by thecodingwizard** [comment]
I've added a test. Please let me know if there's anything else I should change!

File: test/syscalls/linux/pty.cc [hunk 1]
```diff
@@ -1148,6 +1148,23 @@ TEST_F(PtyTest, SwitchNoncanonToCanonNoNewlineBig) {
...
+TEST_F(PtyTest, SwitchCanonToNoncanonEmptyInput) {
+  constexpr char kInput[] = "";
+  ASSERT_THAT(WriteFd(master_.get(), kInput, sizeof(kInput)),
+              SyscallSucceedsWithValue(sizeof(kInput)));
+
+  DisableCanonical();
+
+  // Nothing available yet.
+  char buf[2] = {};
+  ASSERT_THAT(PollAndReadFd(replica_.get(), buf, 2, kTimeout),
```
Comment (ayushr2) [inline test/syscalls/linux/pty.cc:1162]: `kTimeout` is 20 seconds. In the success case, this test will hang for 20 seconds? Its too long. For such successful timeouts, we should use a smaller value like 2 seconds.

File: test/syscalls/linux/pty.cc [hunk 2]
```diff
@@ -1148,6 +1148,23 @@ TEST_F(PtyTest, SwitchNoncanonToCanonNoNewlineBig) {
   ExpectFinished(replica_);
 }
 
+// If the canonical input buffer is empty, and we switch to non-canonical
+// mode, the input buffer should not be readable.
+TEST_F(PtyTest, SwitchCanonToNoncanonEmptyInput) {
+  constexpr char kInput[] = "";
+  ASSERT_THAT(WriteFd(master_.get(), kInput, sizeof(kInput)),
+              SyscallSucceedsWithValue(sizeof(kInput)));
```
[the remark this answers is not in the document]
Comment (thecodingwizard) [reply test/syscalls/linux/pty.cc:1156]: Sounds good. My other PR used `strlen`, which is why I was unsure: https://github.com/google/gvisor/pull/9956/files#r1475131791

File: test/syscalls/linux/pty.cc (hunk 1 above)
Comment (thecodingwizard) [reply test/syscalls/linux/pty.cc:1162]: Makes sense. Is there a constant (like `kSmallTimeout`) I should use, or should I just hardcode it as 2?

Comment (ayushr2) [reply test/syscalls/linux/pty.cc:1162]: I think hard coding here is fine.

File: test/syscalls/linux/pty.cc (hunk 2 above)
[the remark this answers is not in the document]
Comment (ayushr2) [reply test/syscalls/linux/pty.cc:1156]: > Since we don't initialize kInput, strlen() may run off searching for null byte.

Sorry, this is wrong, it is initialized to "" and so there is a null byte. and sizeof() will return 1 while strlen() will return 0.

IIUC, in your other PR, you intend to write "nothing". So strlen there makes sense. Here you intend to write "empty buffer" (only /0 byte) so sizeof would make sense.

**Comment by kevinGC** [comment]
LGTM

File: test/syscalls/linux/pty.cc [hunk 3]
```diff
@@ -1148,6 +1148,23 @@ TEST_F(PtyTest, SwitchNoncanonToCanonNoNewlineBig) {
...
+
+  DisableCanonical();
+
+  // Nothing available yet.
+  char buf[2] = {};
+  ASSERT_THAT(PollAndReadFd(replica_.get(), buf, /* read size */ 2, /* timeout */ 2),
```
Comment (ayushr2) [inline test/syscalls/linux/pty.cc:1162]: Can you rebase on top of https://github.com/google/gvisor/commit/b26cf20d40162945369121a5feaf6162c97bbdfb and use `kTimeoutShort`?

Comment (thecodingwizard) [reply test/syscalls/linux/pty.cc]: done!

**Comment by thecodingwizard** [comment]
@kevinGC is there anything we can do to help get this PR merged? I saw that one of the CI checks is failing; is that something I can help fix? Thanks!

**Comment by ayushr2** [comment]
One of our internal tests was broken last week. Retrying the submit.
