### PR TITLE
pkg/sentry: add cleanup to avoid mntns/FSContext refcount leak

### LINKED ISSUE #12054: Container's MountNamespace refcount leak
### Description

The `runsc exec` command invokes the `execAsync()` function[1] to create a new task. This function increments the reference count of the task's corresponding mount namespace. However, if an error occurs during this process, the reference count is not decremented, resulting in a reference count leak. If the target of the exec is a subcontainer, when this subcontainer exits, its mount namespace will not be released, causing the mount namespace and all associated filesystems to remain in memory, and the corresponding host FD will also not be closed.

1. https://github.com/google/gvisor/blob/release-20250811.0/pkg/sentry/control/proc.go#L184

### Steps to reproduce

I add `runsc debug -print-file-systems <cid>` to dump filesystems of the sandbox:  https://github.com/tianyuzhou95/gvisor/commit/2dfc4a7b1516ece0d58a46e814d3957db4b75ada

```Bash
# create the root container
$ sudo runsc --debug-log=/tmp/runsc/ create --bundle /home/tianyu/pod_test/bundle1 root-container
$ sudo runsc --debug-log=/tmp/runsc/ start root-container

# create the subcontainer
$ sudo runsc --debug-log=/tmp/runsc/ create --bundle /home/tianyu/pod_test/bundle2 app-container
$ sudo runsc --debug-log=/tmp/runsc/ start app-container

# run an exec command that would fail
# Notice: the leak occurs at this step
$ sudo runsc exec app-container /root/entrypoint1
executing processes for container: executing command "/root/entrypoint1" in sandbox: failed to load /root/entrypoint1: permission denied

# check filesystems of the sandbox
$ sudo runsc debug -print-file-systems root-container
$ grep "Filesystem Dump" runsc.log.20250815-113104.003535.boot.txt | grep "11:31" | awk '{print $11}' | sort  | uniq -c
      7 fsType:(*cgroupfs.FilesystemType)(0x21f8de0),
      1 fsType:(*devpts.FilesystemType)(0xc0003c1980),
      2 fsType:(*gofer.FilesystemType)(0x21f8de0),
      1 fsType:host.filesystemType{},
      1 fsType:(*mqfs.FilesystemType)(0x21f8de0),
      1 fsType:nsfs.filesystemType{},
      2 fsType:(*overlay.FilesystemType)(0x21f8de0),
      1 fsType:pipefs.filesystemType{},
      2 fsType:(*proc.FilesystemType)(0x21f8de0),
      1 fsType:sockfs.filesystemType{},
      2 fsType:(*sys.FilesystemType)(0x21f8de0),
      7 fsType:(*tmpfs.FilesystemType)(0x21f8de0),
      1 fsType:(*vfs.anonFilesystemType)(0x21f8de0),

# destroy the subcontainer
$ sudo runsc delete -force app-container

# check filesystems of the sandbox to confirm the leak happens
$ sudo runsc debug -print-file-systems root-container
$ grep "Filesystem Dump" runsc.log.20250815-113104.003535.boot.txt | grep "11:32" | awk '{print $11}' | sort  | uniq -c
      7 fsType:(*cgroupfs.FilesystemType)(0x21f8de0),
      1 fsType:(*devpts.FilesystemType)(0xc0003c1980),
      2 fsType:(*gofer.FilesystemType)(0x21f8de0),
      1 fsType:host.filesystemType{},
      1 fsType:(*mqfs.FilesystemType)(0x21f8de0),
      1 fsType:nsfs.filesystemType{},
      2 fsType:(*overlay.FilesystemType)(0x21f8de0),
      1 fsType:pipefs.filesystemType{},
      2 fsType:(*proc.FilesystemType)(0x21f8de0),
      1 fsType:sockfs.filesystemType{},
      2 fsType:(*sys.FilesystemType)(0x21f8de0),
      7 fsType:(*tmpfs.FilesystemType)(0x21f8de0),
      1 fsType:(*vfs.anonFilesystemType)(0x21f8de0),
```

### runsc version

```shell
runsc version release-20250811.0-20-g584d71e2d441-dirty
spec: 1.2.0
```

### docker version (if using docker)

```shell
N/A
```

### uname

Linux ubuntu-vm 5.15.0-130-generic #140-Ubuntu SMP Wed Dec 18 17:59:53 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### kubectl (if using Kubernetes)

```shell
N/A
```

### repo state (if built from source)

release-20250811.0-21-gfe00998b43

### runsc debug logs (if available)

```shell

```

### PR DESCRIPTION
**Pull request by tianyuzhou95**
Currently, on certain error paths during task creation (e.g., when "runsc exec" fails), we do not properly handle the refcount of the mount namespace, leading to a refcount leak. This patch adds cleanup that would be released before the reference ownership is transferred to callee, ensuring that the refcount is correctly decremented.

Fixes #12054

### CODE REVIEW

File: pkg/sentry/control/proc.go [hunk 1]
```diff
@@ -243,6 +244,8 @@ func (proc *Proc) execAsync(args *ExecArgs) (*kernel.ThreadGroup, kernel.ThreadI
 		initArgs.MountNamespace = proc.Kernel.GlobalInit().Leader().MountNamespace()
 		initArgs.MountNamespace.IncRef()
 	}
```
Comment (ayushr2) [inline pkg/sentry/control/proc.go]: Move line 240-246 up to line 221 and the `mntnsCu` stuff should also go there. That way the `IncRef()` can happen outside the `if` condition and the corresponding defer Decref happens right after it (less error prone):
```
	if initArgs.MountNamespace == nil {
		// Set initArgs so that 'ctx' returns the namespace.
		initArgs.MountNamespace = proc.Kernel.GlobalInit().Leader().MountNamespace()
	}
	// initArgs must hold a reference on MountNamespace, which will
	// be donated to the new process in CreateProcess.
	initArgs.MountNamespace.IncRef()
	mntnsCu := cleanup.Make(func() { initArgs.MountNamespace.DecRef(ctx) })
	defer mntnsCu.Clean()
	...
```

File: pkg/sentry/kernel/kernel.go [hunk 2]
```diff
@@ -1056,6 +1056,8 @@ func (k *Kernel) CreateProcess(args CreateProcessArgs) (*ThreadGroup, ThreadID,
 	// Get the root directory from the MountNamespace.
 	root := mntns.Root(ctx)
 	defer root.DecRef(ctx)
+	mntnsCu := cleanup.Make(func() { mntns.DecRef(ctx) })
+	defer mntnsCu.Clean()
```
Comment (ayushr2) [inline pkg/sentry/kernel/kernel.go]: Seems like a bug... this should only happen in the `if mntns == nil` case above where we are `IncRef()`-ing the `k.globalInit.Leader().MountNamespace()`.

In other cases (where mntns != nil, you have already updated the callers of `Kernel.CreateProcess()` to DecRef() immediately after the mntns is IncRef()-ed.

File: pkg/sentry/control/proc.go (hunk 1 above)
Comment (tianyuzhou95) [reply pkg/sentry/control/proc.go]: Thanks for pointing out! Already changed.

File: pkg/sentry/kernel/kernel.go (hunk 2 above)
Comment (tianyuzhou95) [reply pkg/sentry/kernel/kernel.go]: > In other cases (where mntns != nil, you have already updated the callers of Kernel.CreateProcess() to DecRef() immediately after the mntns is IncRef()-ed.

Actually the caller of `Kernel.CreateProcess()` passes the reference of mntns from `args`, so it is responsible for `Kernel.CreateProcess()` itself to `DecRef()` before it passes reference to `k.tasks.NewTask()`.

In cases when `mntns != nil`, it is better to let `Kernel.CreateProcess()` to `DecRef()` for the caller has no idea whether the error comes from `Kernel.CreateProcess()` or `k.tasks.NewTask()`(the latter will `DecRef()` if error happens), so caller must release mntnsCu before calling `Kernel.CreateProcess()`.

Comment (ayushr2) [reply pkg/sentry/kernel/kernel.go]: Ah you are right, you updated the callers to release `mntnsCu` *before* calling `Kernel.CreateProcess()`.

Could you update the docstring for this function to say something like "Precondition: Caller must take a ref on args.MountNamespace, which is transferred to CreateProcess."

Subsequently, change the "mnt ns reference is transferred to new process" comment in other files to be something like "// mntns ref is transferred to Kernel.CreateProcess()".

It is important to document such reference-ownership rules, similar to how NewTask() documents it: https://github.com/google/gvisor/blob/fc2f4df6597a015d74856e10b2b199af8fe24fee/pkg/sentry/kernel/task_start.go#L117-L118

File: pkg/sentry/kernel/kernel.go [hunk 3]
```diff
@@ -1156,6 +1158,7 @@ func (k *Kernel) CreateProcess(args CreateProcessArgs) (*ThreadGroup, ThreadID,
 	config.UTSNamespace.IncRef()
 	config.IPCNamespace.IncRef()
 	config.NetworkNamespace.IncRef()
+	mntnsCu.Release() // mnt ns reference is transferred to new task
```
Comment (ayushr2) [inline pkg/sentry/kernel/kernel.go]: nit: "new task" => "NewTask()"

Comment (tianyuzhou95) [reply pkg/sentry/kernel/kernel.go]: Thanks, already changed.

File: pkg/sentry/kernel/kernel.go (hunk 2 above)
Comment (tianyuzhou95) [reply pkg/sentry/kernel/kernel.go]: Thanks, already changed.

File: pkg/sentry/kernel/kernel.go [hunk 4]
```diff
@@ -1081,6 +1086,8 @@ func (k *Kernel) CreateProcess(args CreateProcessArgs) (*ThreadGroup, ThreadID,
 		defer wd.DecRef(ctx)
 	}
 	fsContext := NewFSContext(root, wd, args.Umask)
+	fsContextCu := cleanup.Make(func() { fsContext.DecRef(ctx) })
+	defer fsContextCu.Clean()
```
Comment (ayushr2) [inline pkg/sentry/kernel/kernel.go]: You can add to `mntnsCu` itself:
```
mntnsCu.Add(func() { fsContext.DecRef(ctx) })
```

Comment (tianyuzhou95) [reply pkg/sentry/kernel/kernel.go]: Thanks for pointing out, already changed.

I renamed `mntnsCu` to `refcountCu` because it now includes cleanup for multiple types of references.

**Review by ayushr2 — APPROVED** [review]
