### PR TITLE
fuse: Fix MountFuseFilesystem tests failing

### LINKED ISSUE #3360: MountFuseFilesystem tests failing
I 0724 03:04:27.287679  0 [ RUN      ] MountTest.MountFuseFilesystem
I 0724 03:04:27.287680  0 third_party/gvisor/test/syscalls/linux/mount.cc:349: Failure
I 0724 03:04:27.287681  0 Value of: _expr_result
I 0724 03:04:27.287682  0 Expected: is OK
I 0724 03:04:27.287690  0   Actual: PosixError(errno=1 Operation not permitted) mount failed

I 0724 03:04:27.276466  0 [ RUN      ] MountTest.MountFuseFilesystemNoDevice
I 0724 03:04:27.276467  0 third_party/gvisor/test/syscalls/linux/mount.cc:333: Failure
I 0724 03:04:27.276468  0 Value of: mount("", dir.path().c_str(), "fuse", 0, "")
I 0724 03:04:27.276469  0 Expected: -1 (failure), with errno PosixError(errno=22 Invalid argument)
I 0724 03:04:27.276470  0   Actual: -1 (of type int), with errno PosixError(errno=1 Operation not permitted)

### PR DESCRIPTION
**Pull request by craig08**
Before kernel version 4.16-rc6, FUSE mount is protected by `capable(CAP_SYS_ADMIN)`. After this version, it uses `ns_capable(CAP_SYS_ADMIN)` to protect. Before the 4.16 kernel, it was not allowed to mount fuse file systems without the global `CAP_SYS_ADMIN`.

Fixes #3360

### CODE REVIEW

File: test/syscalls/linux/mount.cc [hunk 1]
```diff
@@ -326,6 +326,14 @@ TEST(MountTest, MountFuseFilesystemNoDevice) {
   SKIP_IF(IsRunningOnGvisor() && !IsFUSEEnabled());
 
   auto const dir = ASSERT_NO_ERRNO_AND_VALUE(TempPath::CreateDir());
+
+  // Before kernel version 4.16-rc6, FUSE mount is protected by
+  // capable(CAP_SYS_ADMIN). After this version, it uses
+  // ns_capable(CAP_SYS_ADMIN) to protect. Before the 4.16 kernel, it was not
+  // allowed to mount fuse file systems without the global CAP_SYS_ADMIN.
```
Comment (mrahatm) [inline test/syscalls/linux/mount.cc:333]: Don't we skip this test entirely if we don't have CAP_SYS_ADMIN from line 325? Is there a difference here based on namespaces?

Comment (craig08) [reply test/syscalls/linux/mount.cc:333]: We are able to have `CAP_SYS_ADMIN` but still cannot mount FUSE before kernel 4.16.
```
vagrant@ubuntu1:~$ uname -a
Linux ubuntu1 4.15.0-109-generic #110-Ubuntu SMP Tue Jun 23 02:39:32 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
vagrant@ubuntu1:~$ docker run -it --rm --cap-add SYS_ADMIN --device /dev/fuse ubuntufuse
root@f5877962c374:/fus# ./hello /mnt
fuse: mount failed: Permission denied
```

However, if using kernel after 4.16, there is no error.
```
vagrant@arch:~$ $ uname -a
Linux arch.localdomain 5.7.10-arch1-1 #1 SMP PREEMPT Wed, 22 Jul 2020 19:57:42 +0000 x86_64 GNU/Linux
vagrant@arch:~$ docker run -it --rm --cap-add SYS_ADMIN --device /dev/fuse ubuntufuse
root@320fa68df5f4:/fus# ./hello /mnt
root@320fa68df5f4:/fus#
```

@avagin told me about the commit 4ad769f3c346ec3d458e255548dec26ca5284cf6 in Linux source code, it adds `FS_USERNS_MOUNT` flag into FUSE mount. This is introduced in `v4.16-rc6-11-g4ad769f3c346` revision.
```
commit 4ad769f3c346ec3d458e255548dec26ca5284cf6
Author: Eric W. Biederman <ebiederm@xmission.com>
Date:   Tue May 29 09:04:46 2018 -0500

    fuse: Allow fully unprivileged mounts

    Now that the fuse and the vfs work is complete.  Allow the fuse filesystem
    to be mounted by the root user in a user namespace.

    Signed-off-by: "Eric W. Biederman" <ebiederm@xmission.com>
    Signed-off-by: Miklos Szeredi <mszeredi@redhat.com>

diff --git a/fs/fuse/inode.c b/fs/fuse/inode.c
index 22c76cf8c2e3..48baa26993f3 100644
--- a/fs/fuse/inode.c
+++ b/fs/fuse/inode.c
@@ -1222,7 +1222,7 @@ static void fuse_kill_sb_anon(struct super_block *sb)
 static struct file_system_type fuse_fs_type = {
        .owner          = THIS_MODULE,
        .name           = "fuse",
-       .fs_flags       = FS_HAS_SUBTYPE,
+       .fs_flags       = FS_HAS_SUBTYPE | FS_USERNS_MOUNT,
        .mount          = fuse_mount,
        .kill_sb        = fuse_kill_sb_anon,
 };
```

Comment (avagin) [reply test/syscalls/linux/mount.cc:333]: @mrahatm We check CAP_SYS_ADMIN in the current user namespace. But before 4.16, it requires the global CAP_SYS_ADMIN. In the linux source, there are two helpers ns_capable and capable.
