### PR TITLE
fix missing SIGTTOU signal in SetForegroundProcessGroup

### LINKED ISSUE #6148: Send SIGTTOU to processes sent to background
From `tcsetpgrp(3)`:

> If tcsetpgrp() is called by a member of a background process group in its session, and the calling process is not blocking or ignoring SIGTTOU, a SIGTTOU signal is sent to all members of this background process group.

### PR DESCRIPTION
**Pull request by gystemd**
SetForegroundProcessGroup now send a SIGTTOU signal if called by a process belonging to a background group. Fixes #6148

### CODE REVIEW

File: pkg/sentry/kernel/thread_group.go [hunk 1]
```diff
@@ -516,6 +511,11 @@ func (tg *ThreadGroup) SetForegroundProcessGroup(tty *TTY, pgid ProcessGroupID)
 		return -1, linuxerr.EPERM
 	}
 
+	//if the calling process is a member of a background group, a SIGTTOU signal is sent to all members of this background process group.
+	if tg.processGroup.session.foreground.id != tg.processGroup.id {
```
Comment (kevinGC) [inline pkg/sentry/kernel/thread_group.go:515]: I believe we also need to check whether the calling process (`tg` here) is blocking or ignoring `SIGTTOU`:

> If tcsetpgrp() is called by a member of a background process group in its session, **and the calling process is not blocking or ignoring SIGTTOU**, a SIGTTOU signal is sent to all members of this background process group.

This is also something worth testing.

File: pkg/sentry/kernel/thread_group.go [hunk 2]
```diff
@@ -516,6 +511,11 @@ func (tg *ThreadGroup) SetForegroundProcessGroup(tty *TTY, pgid ProcessGroupID)
 		return -1, linuxerr.EPERM
 	}
 
+	//if the calling process is a member of a background group, a SIGTTOU signal is sent to all members of this background process group.
```
Comment (kevinGC) [inline pkg/sentry/kernel/thread_group.go:514]: Formatting nit: comments are usually capitalized and wrapped at 80 characters, so this would be:
```go
  // If the calling process is a member of a background group, a SIGTTOU signal
  // is sent to all members of this background process group.
```

**Review by kevinGC — COMMENTED** [review]
Thanks for the PR. I think this change should have a test as well. See [this test in //test/syscalls/linux/pty.cc](https://cs.opensource.google/gvisor/gvisor/+/master:test/syscalls/linux/pty.cc;l=1598) for an example that could be copied+modified to check that we're sending SIGTTOU when appropriate.

File: pkg/sentry/kernel/thread_group.go (hunk 1 above)
Comment (gystemd) [reply pkg/sentry/kernel/thread_group.go]: > I believe we also need to check whether the calling process (`tg` here) is blocking or ignoring `SIGTTOU`:
> 
> > If tcsetpgrp() is called by a member of a background process group in its session, **and the calling process is not blocking or ignoring SIGTTOU**, a SIGTTOU signal is sent to all members of this background process group.
> 
> This is also something worth testing.

I'm sorry, I assumed that if the process neglects the signal, the latter isn't sent at all. I did add a check to verify if the process is ignoring the SIGTTOU and another test as well for this case (SetForegroundProcessGroupSIGTTOUIgnored).

File: test/syscalls/linux/pty.cc [hunk 3]
```diff
@@ -1640,6 +1640,57 @@ TEST_F(JobControlTest, DISABLED_SetForegroundProcessGroup) {
   ASSERT_NO_ERRNO(res);
 }
 
+// This test verify if a SIGTTOU signal is sent to the calling process'group
+// when tcsetpgrp is called by a background process
+TEST_F(JobControlTest, SetForegroundProcessGroupSIGTTOUBackground) {
+  auto res = RunInChild([=]() {
+    setsid();
```
Comment (kevinGC) [inline test/syscalls/linux/pty.cc:1647]: All the calls to `setsid()`, `setpgid()`, and `tcsetpgrp()` should be checked via `TEST_PCHECK()`. Both here and in the below test.

File: test/syscalls/linux/pty.cc [hunk 4]
```diff
@@ -1640,6 +1640,57 @@ TEST_F(JobControlTest, DISABLED_SetForegroundProcessGroup) {
   ASSERT_NO_ERRNO(res);
 }
 
+// This test verify if a SIGTTOU signal is sent to the calling process'group
```
Comment (kevinGC) [inline test/syscalls/linux/pty.cc:1643]: Nit: space between process' and group.

File: test/syscalls/linux/pty.cc [hunk 5]
```diff
@@ -1640,6 +1640,57 @@ TEST_F(JobControlTest, DISABLED_SetForegroundProcessGroup) {
...
+// when tcsetpgrp is called by a background process
+TEST_F(JobControlTest, SetForegroundProcessGroupSIGTTOUBackground) {
+  auto res = RunInChild([=]() {
+    setsid();
+    TEST_PCHECK(!ioctl(replica_.get(), TIOCSCTTY, 0));
+    pid_t grandchild = fork();
+    if (!grandchild) {
+        //assign a different pgid to the child so it will result as
```
Comment (kevinGC) [inline test/syscalls/linux/pty.cc:1651]: Nit: for consistency, comments start with a space and are full sentences with capitals like:
```cpp
// Assign a different pgid to the child so it will result as
// a background process.
```
This applies to below comments too.

File: test/syscalls/linux/pty.cc [hunk 6]
```diff
@@ -1640,6 +1640,57 @@ TEST_F(JobControlTest, DISABLED_SetForegroundProcessGroup) {
...
+        //a background process
+        setpgid(grandchild, getpid());
+        tcsetpgrp(replica_.get(), getpgid(0));
+          // We should never reach this.
+          _exit(1);
```
Comment (kevinGC) [inline test/syscalls/linux/pty.cc:1656]: Indentation seems off.

File: test/syscalls/linux/pty.cc [hunk 7]
```diff
@@ -1640,6 +1640,57 @@ TEST_F(JobControlTest, DISABLED_SetForegroundProcessGroup) {
...
+        }
+    int wstatus;
+    TEST_PCHECK(waitpid(grandchild, &wstatus, WSTOPPED) == grandchild);
+    TEST_PCHECK(WSTOPSIG(wstatus)==SIGTTOU);
```
Comment (kevinGC) [inline test/syscalls/linux/pty.cc:1660]: Nit: for consistency:
```cpp
TEST_PCHECK(WSTOPSIG(wstatus) == SIGTTOU);
```

File: test/syscalls/linux/pty.cc [hunk 8]
```diff
@@ -1640,6 +1640,57 @@ TEST_F(JobControlTest, DISABLED_SetForegroundProcessGroup) {
...
+        sa.sa_handler = SIG_IGN;
+        sa.sa_flags = 0;
+        sigemptyset(&sa.sa_mask);
+        sigaction(SIGTTOU, &sa, NULL);
+        //assign a different pgid to the child so it will result as
+        //a background process
+        setpgid(grandchild, getpid());
+        tcsetpgrp(replica_.get(), getpgid(0));
+        _exit(0);
+        }
```
Comment (kevinGC) [inline test/syscalls/linux/pty.cc:1685]: Indentation seems off.

File: test/syscalls/linux/pty.cc [hunk 9]
```diff
@@ -1640,6 +1640,57 @@ TEST_F(JobControlTest, DISABLED_SetForegroundProcessGroup) {
...
+    int wstatus;
+    TEST_PCHECK(waitpid(grandchild, &wstatus, WSTOPPED) == grandchild);
+    TEST_PCHECK(WSTOPSIG(wstatus)!=SIGTTOU);
```
Comment (kevinGC) [inline test/syscalls/linux/pty.cc:1688]: Nit: for consistency:
```cpp
TEST_PCHECK(WSTOPSIG(wstatus) != SIGTTOU);
```

**Review by kevinGC — COMMENTED** [review]
Just minor stuff left.

File: pkg/sentry/kernel/thread_group.go (hunk 1 above)
Comment (kevinGC) [reply pkg/sentry/kernel/thread_group.go]: There should also be a check for whether the process is blocking SIGTTOU, which can be done via [`task.SignalMask()`](https://cs.opensource.google/gvisor/gvisor/+/master:pkg/sentry/kernel/task_signals.go;l=587;bpv=0;bpt=0). I believe you can reuse the test you wrote for ignoring to also check for blocking.

**Comment by gystemd** [comment]
@kevinGC Thank you, Now I think I've fixed all the issues you pointed out.
